### ISSUE TITLE
PageRank (Segmentation Fault)

### ISSUE THREAD

**Issue by souravpati** [realstolz/polymer#8]
Hi,
I was using polymer to run some experiments. I was unable to run PageRank. It gives segmentation fault. I used the same set of datasets as I used for Ligra.

**Comment by Lxiucai** [comment]
Hava you solved this problem?

**Comment by souravpati** [comment]
I was able to solve the problem.

**Comment by Lxiucai** [comment]
I encountered this problem again. Can you tell me how you solved it?

**Comment by souravpati** [comment]
I did not. I realized later that I downloaded the snapshot from http://ipads.se.sjtu.edu.cn/projects/polymer.html and the PageRank from this seems to work fine. I was about to inform that the current Github version for PageRank doesn't work.

**Comment by Lxiucai** [comment]
Thanks  a lot. There seems to be problem on BP ,SPMV. Have you encountered these problems?

**Comment by souravpati** [comment]
No, I did not need that for my application.

**Comment by Lxiucai** [comment]
Thanks a lot.

**Comment by realstolz** [comment]
Currently, we focus on meeting a deadline, which need about one week. Sorry, please be patient.

**Comment by Lxiucai** [comment]
I will wait patiently. Wish you work smoothly.

**Comment by realstolz** [comment]
Could you provide your script command and dataset information?

**Comment by Raphus-cucullatus** [comment]
@Lxiucai I found a bug and create a pull request #9, does it help

**Comment by Lxiucai** [comment]
I can already run bfs and pagerank correctly，thank you very much.
